### ISSUE TITLE
for snpe_detection project, anything wrong with this?

### ISSUE THREAD

**Issue by jxr041100** [quic/sample-apps-for-robotics-platforms#48]
sh-4.4# ./snpe_detection 
gbm_create_device(156): Info: backend name is: msm_drm
Not all elements could be created.

**Comment by sahilbm** [comment]
Hi Jeff,
Can you please share the output for the command given below,

> gst-inspect-1.0 qtimlesnpe

It might be causing because of the some of the element from the Gstreamer pipeline created in snpe-detection.c are not available.

**Comment by mayur-mk** [comment]
Hi , 

**qtimlesnpe Gstreamer plugin not available on RB5.**

You can try TFlite Gstreamer plugin for object detection. 
You can find source code [https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/tree/master/Gstreamer-Applications/gst_tflite](url) 
or 
[https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/tree/master/gst-python-samples/Gstreamer-Applications/gst_tflite](url)

Thanks & Regards, 
Mayur

**Comment by AftermathK** [comment]
Hi @mayur-mk, 

Thank you for the update on this; is the qtimlesnpe gstreamer pluging part of the LE build? If so, what are the tradeoffs?

For the LU build specifically, is there an alternative for loading DLC models in C++? Thanks.

**Comment by sahilbm** [comment]
Hi @AftermathK ,

As considering the LE or LU Building, Please try with the latest build of the LE, it might have the support for the Same.
But if you are asking specifically for LU, I would recommend you to go ahead and make use of SNPE SDK, to build the C++ based Inference on the DLC Model.

Please let me know if you need any guidance on the same.

**Comment by AftermathK** [comment]
@sahilbm Thank you for the response; I'll keep the LE build in mind. Is there a complete doc. that describes the differences and support provided for each build? Thanks again.

**Comment by bmsahil** [comment]
@AftermathK , As per my knowledge there is no specific document which explains you the what is LE and LU, But I can comment on high level that LU is ubuntu based edition where as LE is Debian might be. The support for LE was added in RB5's SDK Manager recently.

As I can see we are deviating from the main question, 
@jxr041100, @XW-HKU & @AftermathK ,
For using the qtimlesnpe element in your current build, Please try to build & install the Gstreamer SNPE's elment.
Please refer the README given in below URL in order to setup the same:
https://github.com/quic/sample-apps-for-Qualcomm-Robotics-RB5-platform/tree/master/gst_mle_oss/gst_snpe

Hope this will the resolve the problem.
